### ISSUE TITLE
Setup-zig action is presenting unstable behavior and needs investigation

### ISSUE THREAD

**Issue by rbarker-dev** [hiero-ledger/hiero-cryptography#118]
Investigate setup-zig process; it takes either seconds or hours to complete. Need to understand why and if we can speed this up.

**Comment by andrewb1269** [comment]
This is probably related to issue #125

**Comment by rbarker-dev** [comment]
release engineering is investigating known issues with azure mirrors on one of the self-hosted clusters. Investigation turned over to them.
