### ISSUE TITLE
Fix publishing to Maven Central

### ISSUE THREAD

**Issue by andrewb1269** [hiero-ledger/hiero-cryptography#120]
In Issue #91 there was a problem identified with actually publishing to maven central.

See this [action link here.](https://github.com/hashgraph/hedera-cryptography/actions/runs/11744616918/job/32720203867)

There appear to be two issues:

1. Could not read PGP secret key.

2. 5 problems were found storing the configuration cache, 2 of which seem unique.

**Comment by rbarker-dev** [comment]
In `.github/workflows/zxc-release-maven-central.yaml` we can remove the 
```
          SIGNING_KEY: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
```

This will align the file with what we do in other repositories

**Comment by andrewb1269** [comment]
Also follow up with Nathan to see how to do appropriate testing on the publishing step. Do we end up wasting v 1.0.0 in testing?
EDIT: Meeting with Nathan scheduled on Monday morning to discuss.

**Comment by andrewb1269** [comment]
This issue is related to #90

**Comment by andrewb1269** [comment]
Reopening as there is some additional work to be done.

**Comment by andrewb1269** [comment]
Nathan has merged to the mainline. I'm merging additional changes to the mainline and the publishing step will be complete.

There will be additional steps captured in this effort: #126 
Consolidate the workflows from 2 to 1, then move some pieces of the workflow into the `.releaserc` file.
