### ISSUE TITLE
hedera-cryptography fails to build locally

### ISSUE THREAD

**Issue by andrewb1269** [hiero-ledger/hiero-cryptography#125]
`feature.rust.gradle.kts` file, function `installCargoCrossCompiler` installs the compiler locally every time and recompiles , which is inefficient.

`zigbuild` cannot be found through running `./gradlew assemble` but can be found when running `zigbuild` without the `--target=<target>` arg. This has been resolved with PR #127

**Comment by andrewb1269** [comment]
@rbarkerSL @jjohannes 

Jendrik - please take a look at the comment about the `installCargoCrossCompiler` issue. Rather than installing the compiler every run, we should only install the compiler if it is not already installed on the machine doing the build.

**Comment by rbarker-dev** [comment]
Adding to this the zigbuild task fails if zig is already present on the users computer and the build task fails when the `target` parameter is set outside of gnu windows.

**Comment by rbarker-dev** [comment]
Can we update the gradle tasks to include setup zig for local builds?

The ./gradlew assemble task will fail if someone doesn't follow the readme and just does a clone and assemble on the project

**Comment by andrewb1269** [comment]
There are errors that will be pumped out when running `gradle assemble` then it'll fail. Can we publish more clear error messages so we know we need to install zig for local builds?

**Comment by rbarker-dev** [comment]
aarch64-unknown-linux-gnu target may also be needed

**Comment by andrewb1269** [comment]
Potentially need to add the `msvc` and `unknown-linux-gnu` flavor targets as they might not be installed by default.

**Comment by jjohannes** [comment]
@andrewb1269hg @rbarkerSL I would like to have a chat about this to decide which experience we want and how to best implement it. We can coordinate at our meeting on Wednesday.

**Comment by jjohannes** [comment]
Summary of chat:

1. `cargo install --locked cargo-zigbuild` done by Gradle fails in certain setups and that should be fixed
   - @jjohannes wasn't able to reproduce it locally. Running `./gradlew assemble` runs smoothly multiple times when working on Rust code
   - @rbarkerSL will look into sharing steps to reproduce

2. Make it possible to clone repo and run `./gradlew assemble` on any machine [without reading the requirements Readme section in the Readme](https://github.com/hashgraph/hedera-cryptography?tab=readme-ov-file#requirements). 
   - [ ] TODO @jjohannes see how much of the installation can be moved into Gradle. For the parts that we can't move easily, give a clear error message to the user what she needs to install manually first. Similar to how we warn for the wrong Java version.

**Comment by andrewb1269** [comment]
@jjohannes here's a screenshot of the error:

![Zigbuild Failure](https://github.com/user-attachments/assets/36e82777-df33-49fd-a083-9423dde3d4a2)

**Comment by jjohannes** [comment]
Eventually, I decided to attempt the whole installation process in isolation thought Gradle (instead of just giving better errors). PR for that approach: https://github.com/hashgraph/hedera-cryptography/pull/159
