### ISSUE TITLE
Create and configure `develop` branch

### ISSUE THREAD

**Issue by litt3** [hiero-ledger/hiero-cryptography#15]
This repo should use `develop` instead of `main`

**Comment by nathanklick** [comment]
@rbarkerSL This ticket should not be implemented. This repository should follow the Feature Branch git branching model described in [this notion page](https://www.notion.so/swirldslabs/002-Git-Branching-Strategy-d39b1b2a485e401ba8971e521d46a3c1?pvs=4#9936a9f89a82454bb962f59ac4428b2a).

Please refer to the [hashgraph/solo](https://github.com/hashgraph/solo) repository for an example. Additionally, it is strongly recommended to follow and enforce the conventional commit standard and the use the `semantic-release` tooling to issue release artifacts and notes.
