### ISSUE TITLE
Update `gradle-build-action` to `setup-gradle`

### ISSUE THREAD

**Issue by rbarker-dev** [hiero-ledger/hiero-cryptography#152]
- [ ] All instances of `gradle/gradle-build-action` are replaced
  - [ ] The `gradle/actions/setup-gradle` action is set on each workflow (once per job)
  - [ ] The calls to `gradle-build-action` are replaced with their appropriate `./gradlew` calls

**Comment by andrewb1269** [comment]
![image](https://github.com/user-attachments/assets/5269f22b-3275-4a61-b89d-8eef16c4060d)

**Comment by andrewb1269** [comment]
you change the action to that

 then wherever you see gradle-build-action you will either have setup-gradle OR you will change it to run: ./gradlew ...

if there's an arguments property on the gradle-build-action, that property is now deprecated as well

so it becomes run: `./gradlew <content of arguments property>`
