### ISSUE TITLE
Evaluate current BLS Loader / consider other options

### ISSUE THREAD

**Issue by litt3** [hiero-ledger/hiero-cryptography#8]
Is the current setup actually how we want it?

From https://github.com/hashgraph/hedera-bls-cryptography/pull/3#discussion_r1092235720

**Comment by litt3** [comment]
Having spoken with @cody-littley about this, I believe we've settled into the position that the current `BLSLoader` structure is *not* desirable.

A couple thoughts:
- using the static loader would make unit testing of different implementations of the public API difficult (since the loader just returns that first implementation found in the java classpath)
- all nodes on the network need to have the same implementation of the BLS cryptography anyway. it isn't possible for different nodes to use different implementations (since there isn't any standard serialization format for `Gt` group elements)
    - There is little value in dynamically loading in an implementation from the classpath, since all nodes need to agree on an implementation in advance anyway


With all this in mind, passing in the desired implementation via the "platform builder" strategy is better than being fancy and loading in the resource via magic

**Comment by cody-littley** [comment]
👍 to what Austin wrote above. Static stateful objects are evil, and setting the implementation of a library globally will make it tricky to unit test different implementations. Once we invert control and get a platform builder API, the BLS cryptography library should be one of many implementations that the app can decide to swap out for whatever implementation it wants.

**Comment by nathanklick** [comment]
@cody-littley The service loader implementation in this project is the standard way to load one or more SPI implementations registered using the native Java SPI framework. The above is not a stateful static object in the traditional sense and could easily be extended to allow selection of the desired SPI implementation. 

The ServiceLoader discovery method can be easily used in conjunction with a builder model.
