### ISSUE TITLE
Rust: Windows DLL loading is not using correct file name

### ISSUE THREAD

**Issue by jjohannes** [hiero-ledger/hiero-cryptography#81]
### Description

The DLL compiled for Windows does not have the `lib` prefix, which means for the library `bn254` the file is called `bn254.dll` and **not** `libbn254.dll`.

We could probably rename the file as part of the build if we want that solution, but maybe it is more consistent with common standards to not prepend the "lib" prefix for Windows in the loading code.

### Steps to reproduce

I created a setup that runs the `hedera-cryptography-altbn128` tests on Windows on CI on top of #70.
It's failing to load the file, although it was created.
- https://github.com/hashgraph/hedera-cryptography/actions/runs/11363866764/job/31608808094
- https://scans.gradle.com/s/q23d7xbiz4cc2/tests/overview

### Version

develop

### Operating system

Windows

**Comment by jjohannes** [comment]
I prepared a PR for running the tests on CI on Windows/Mac.

If you start working on this, you may use that to test if you do not have a local Windows environment.

https://github.com/hashgraph/hedera-cryptography/pull/82

**Comment by mxtartaglia-sl** [comment]
@timo0 It would be very good feedback how you find interacting with the build process @jjohannes was working.
As I have most of the necessary things already installed.

**Comment by mxtartaglia-sl** [comment]
@poulok this one is in hedera-cryptography repo, I don't know if its gonna show up in burncharts and your reports

**Comment by jjohannes** [comment]
Anther small thing: https://github.com/hashgraph/hedera-cryptography/pull/82#discussion_r1804948461
Added a fix to #82.
