### ISSUE TITLE
Enable conventional commit & semantic release workflow

### ISSUE THREAD

**Issue by rbarker-dev** [hiero-ledger/hiero-cryptography#91]
- Ensure conventional commit is enforced in the rule checks
- Verify windows and mac cross-compile is working and generating all needed outputs

See example in [solo](https://github.com/hashgraph/solo/blob/main/.github/workflows/flow-deploy-release-artifact.yaml) for semantic release / conventional commits

Implemented using the approach in `full-stack-testing` repo.

Tested using dry-run enabled and by changing the `.releaserc` config file to be individual branch name instead of `main`.

Commented out the actual publish steps as we did not want to publish from a private branch.

**Comment by andrewb1269** [comment]
We need to consider if doing `semantic releases` with `npm` to `maven` is the right approach.

There appears to be a `maven-semantic-release` repository [here](https://github.com/conveyal/maven-semantic-release) that is functionally very similar or equivalent to the `npm semantic release` package.

**Comment by andrewb1269** [comment]
Follow gradle example here:
https://github.com/hashgraph/full-stack-testing/blob/main/.github/workflows/flow-deploy-release-artifact.yaml

Copy and implement the `.releaserc` file and update as appropriate:
https://github.com/hashgraph/full-stack-testing/blob/main/.releaserc

**Comment by andrewb1269** [comment]
Draft PR ready to discuss with Roger. Discussing this afternoon.
